group=io.github.username.template
version=26.2
# description=
runVersion=26.2
plugin.name=Template
# plugin.prefix=
# plugin.website="https://github.com/username/template"
# plugin.author=username
plugin.main=Main
plugin.apiVersion=26.2
plugin.bootstrapper=Bootstrap
# plugin.loader=Load
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4096M
